name: Send CI Run Result

# Determines after which workflows this workflow will execute.
on:
  workflow_run:
    workflows: 
      - CI
    types: 
      - completed

jobs:
  # This job will perform a HTTP POST to any endpoint
  # you set up your web hook
  send-webhook-notification:
    runs-on: ubuntu-latest

    # (OPTIONAL) Include the environment below if you are
    # setting up your secrets against an environment
    environment:
      name: Production

    # Using a custom action built by github user (distributhor).
    # See https://github.com/marketplace/actions/workflow-webhook-action 
    # for more details
    steps:
      - name: Send Action Run Result to Webhook        
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "conclusion": "${{ github.event.workflow_run.conclusion }}" }'
